/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    RetainerAccess: {
      address: "0xd3A218AD4c817B14Cc754e4c996A95435155a27B",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "beneficiary_",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "pricePerPeriod_",
              type: "uint256",
            },
            {
              internalType: "uint32",
              name: "periodSeconds_",
              type: "uint32",
            },
          ],
          stateMutability: "payable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "AlreadyActive",
          type: "error",
        },
        {
          inputs: [],
          name: "Insolvent",
          type: "error",
        },
        {
          inputs: [],
          name: "InsufficientBalance",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidTerms",
          type: "error",
        },
        {
          inputs: [],
          name: "NotBeneficiary",
          type: "error",
        },
        {
          inputs: [],
          name: "NotSubscribed",
          type: "error",
        },
        {
          inputs: [],
          name: "NothingToFund",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "int64",
              name: "responseCode",
              type: "int64",
            },
          ],
          name: "ScheduleFailed",
          type: "error",
        },
        {
          inputs: [],
          name: "TermsNotSet",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "nowTs",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "expiresAt",
              type: "uint256",
            },
          ],
          name: "TooEarly",
          type: "error",
        },
        {
          inputs: [],
          name: "TransferFailed",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "agent",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "refunded",
              type: "uint256",
            },
          ],
          name: "Cancelled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "agent",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "balance",
              type: "uint256",
            },
          ],
          name: "Funded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "reserve",
              type: "uint256",
            },
          ],
          name: "GasReserveFunded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "agent",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "reason",
              type: "string",
            },
          ],
          name: "Lapsed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "agent",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "schedule",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "reclaimed",
              type: "uint256",
            },
          ],
          name: "RenewalCancelled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "agent",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "schedule",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "firesAt",
              type: "uint256",
            },
          ],
          name: "RenewalScheduled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "agent",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "paid",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "expiresAt",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "balance",
              type: "uint256",
            },
          ],
          name: "Renewed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "agent",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "pricePerPeriod",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint32",
              name: "periodSeconds",
              type: "uint32",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "expiresAt",
              type: "uint256",
            },
          ],
          name: "SubscriptionStarted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "pricePerPeriod",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint32",
              name: "periodSeconds",
              type: "uint32",
            },
          ],
          name: "TermsSet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "Withdrawn",
          type: "event",
        },
        {
          inputs: [],
          name: "MIN_PERIOD_SECONDS",
          outputs: [
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "RENEWAL_COST_ESTIMATE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "beneficiary",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "cancel",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "agent",
              type: "address",
            },
          ],
          name: "creditFor",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "fund",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "fundGasReserve",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "gasReserve",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "agent",
              type: "address",
            },
          ],
          name: "hasAccess",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owed",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "periodSeconds",
          outputs: [
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "pricePerPeriod",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "agent",
              type: "address",
            },
          ],
          name: "renew",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "renewalsRemaining",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "revenue",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "pricePerPeriod_",
              type: "uint256",
            },
            {
              internalType: "uint32",
              name: "periodSeconds_",
              type: "uint32",
            },
          ],
          name: "setTerms",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "subscribe",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "agent",
              type: "address",
            },
          ],
          name: "subscribeFor",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "agent",
              type: "address",
            },
          ],
          name: "subscriptionOf",
          outputs: [
            {
              internalType: "uint256",
              name: "balance",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "expiresAt",
              type: "uint256",
            },
            {
              internalType: "uint32",
              name: "period",
              type: "uint32",
            },
            {
              internalType: "bool",
              name: "active",
              type: "bool",
            },
            {
              internalType: "address",
              name: "schedule",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "syncReserve",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 40241011,
      hederaContractId: "0.0.10414167",
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
